baseURL = "https://jonathanmlowery.com/"
staticDir = "static"
languageCode = "en-us"
title = "Jonathan Lowery"
theme = "nightfall"

[markup.goldmark.renderer]
  unsafe= true

[params]
  user = "user"
  hostname = "jonathanmlowery.com"
  location = "Eldersburg, MD"
 

  [params.author]
    name = "Jonathan Lowery"
    email = "contact@jonathanmlowery.com"
    avatarFirst = true
    avatar = "/avatar.png"
    avatarSize = "size-m"

  [[params.social]]
    key = 0
    name = "Github"
    url = "https://github.com/jonathanmlowery"
    icon = "fa-brands fa-github"
    target = "_blank"
    aria = "GitHub Profile"

  [[params.social]]
    key = 1
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jonathan-lowery-724a7524a"
    icon = "fa-brands fa-linkedin"
    target = "_blank"
    aria = "LinkedIn Profile"

[[menu.header]]
  name = "home"
  url = "/"
  weight = 1
[[menu.header]]
  name = "cli"
  url = "/cli/"
  weight = 2
[[menu.header]]
  name = "blog"
  url = "/blog/"
  weight = 3