[build]
  command = "curl -L -o sass.tar.gz https://github.com/sass/dart-sass-embedded/releases/download/1.62.1/sass_embedded-1.62.1-linux-arm64.tar.gz && tar -xzf sass.tar.gz && mv dart-sass-embedded/dart-sass-embedded /usr/local/bin/ && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.6"
  DART_SASS_EMBEDDED = "/usr/local/bin/dart-sass-embedded"